---
abstract: 'use Cassandra databases with L<IO::Async> using CQL'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::Test: 0
  Test::Fatal: 0
  Test::HexString: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-CassandraCQL
provides:
  Net::Async::CassandraCQL:
    file: lib/Net/Async/CassandraCQL.pm
    version: 0.04
  Net::Async::CassandraCQL::Query:
    file: lib/Net/Async/CassandraCQL/Query.pm
    version: 0.04
requires:
  Future: 0.13
  IO::Async::Loop: 0.54
  IO::Async::Protocol::Stream: 0
  Protocol::CassandraCQL: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
